### ISSUE TITLE
можно компактнее

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-Class-syntax#1]
https://github.com/Alex-it-work/JS-Class-syntax/blob/f7c00315856dff76312c9f063ad42a2d93ca6bfa/js/index.js#L18
https://github.com/Alex-it-work/JS-Class-syntax/blob/f7c00315856dff76312c9f063ad42a2d93ca6bfa/js/index.js#L19
- строки можно совместить

**Comment by Alex-it-work** [comment]
есть
