### ISSUE TITLE
скорость

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-Class-syntax#2]
https://github.com/Alex-it-work/JS-Class-syntax/blob/f7c00315856dff76312c9f063ad42a2d93ca6bfa/js/index.js#L62
- по скорости, не думаю, что не особо разница есть, порядок остается тот же (я про сложность алгоритмов), главное, что не вложенные циклы. Но двумя явно легче воспринимается.

**Comment by Alex-it-work** [comment]
спасибо
